
# -*- coding: utf-8 -*-
"""Train_LogReg_Colab.ipynb

Automatically generated by Colaboratory.

# Gender Classification: Logistic Regression
"""

import os
# Auto-install dependencies
os.system('pip install scikit-image scikit-learn kagglehub tqdm')

import numpy as np
import joblib
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from skimage import io
from skimage.transform import resize
from tqdm import tqdm

# Dataset
try:
    import kagglehub
except ImportError:
    os.system('pip install kagglehub')
    import kagglehub

print("Downloading Dataset...")
dataset_path = kagglehub.dataset_download("cashutosh/gender-classification-dataset")
train_dir = os.path.join(dataset_path, 'Training')
val_dir = os.path.join(dataset_path, 'Validation')

def extract_features(directory, limit_per_class=5000):
    features = []
    labels = []
    
    for label_name in ['female', 'male']:
        label_dir = os.path.join(directory, label_name)
        if not os.path.isdir(label_dir): 
             label_name = label_name.capitalize()
             label_dir = os.path.join(directory, label_name)

        label_idx = 0 if 'female' in label_name.lower() else 1
        
        print(f"Processing {label_name}...")
        count = 0
        for img_name in tqdm(os.listdir(label_dir)):
            if count >= limit_per_class: break
            
            img_path = os.path.join(label_dir, img_name)
            try:
                img = io.imread(img_path)
                img = resize(img, (64, 64))
                # Flatten: (64, 64, 3) -> 12288
                flat = img.flatten()
                
                features.append(flat)
                labels.append(label_idx)
                count += 1
            except: pass
                
    return np.array(features), np.array(labels)

# Extract Features
print("Extracting Training Features...")
X_train, y_train = extract_features(train_dir)
print(f"Training Shape: {X_train.shape}")

print("Extracting Validation Features...")
X_val, y_val = extract_features(val_dir)

# Train LogReg
print("Training Logistic Regression...")
# Use 'saga' solver for larger datasets, 'lbfgs' is default but might be slow or not converge without scaling
# Normalize data? Images are 0-1 from resize, so relatively scaled.
clf = LogisticRegression(solver='saga', max_iter=100) 
clf.fit(X_train, y_train)

# Evaluate
print("Evaluating...")
y_pred = clf.predict(X_val)
acc = accuracy_score(y_val, y_pred) * 100
print(f"Validation Accuracy: {acc:.2f}%")

# Save
save_path = 'gender_logreg.pkl'
joblib.dump(clf, save_path)
print(f"Saved to {save_path}")

try:
    from google.colab import files
    files.download(save_path)
except: pass
