
# -*- coding: utf-8 -*-
"""Train_Gender_CNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1...

# Custom CNN Training for Gender Classification
This script trains a Convolutional Neural Network (CNN) from scratch to classify gender (Male/Female).
"""

import os
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
import matplotlib.pyplot as plt
import numpy as np

# Check device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# ==========================================
# 1. Dataset Preparation
# ==========================================
# Install kagglehub if not present
try:
    import kagglehub
except ImportError:
    os.system('pip install kagglehub tqdm')
    import kagglehub

def setup_data():
    print("Downloading Dataset using kagglehub...")
    # Download latest version
    path = kagglehub.dataset_download("cashutosh/gender-classification-dataset")
    print(f"Path to dataset files: {path}")
    return path

# Call setup
dataset_path = setup_data()

# Data Transforms (Augmentation + Normalization)
train_transforms = transforms.Compose([
    transforms.Resize((100, 100)), # Resize to smaller standard size
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(10),
    transforms.ToTensor(),
    transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5]) # Normalize to [-1, 1]
])

test_transforms = transforms.Compose([
    transforms.Resize((100, 100)),
    transforms.ToTensor(),
    transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5])
])

# Load Data
# kagglehub downloads to a cache path. We look for 'Training' and 'Validation' inside.
train_dir = os.path.join(dataset_path, 'Training')
val_dir = os.path.join(dataset_path, 'Validation')

if not os.path.exists(train_dir):
    # Depending on dataset structure, might need to adjust
    print(f"Checking directory structure... Found: {os.listdir('.')}")

train_dataset = datasets.ImageFolder(train_dir, transform=train_transforms)
val_dataset = datasets.ImageFolder(val_dir, transform=test_transforms)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False)

print(f"Classes: {train_dataset.classes}") # ['female', 'male']

# ==========================================
# 2. Define Custom CNN Architecture
# ==========================================
class GenderCNN(nn.Module):
    def __init__(self):
        super(GenderCNN, self).__init__()
        
        # Block 1
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.bn1 = nn.BatchNorm2d(32)
        self.relu = nn.ReLU()
        self.pool = nn.MaxPool2d(2, 2) # 100x100 -> 50x50

        # Block 2
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.bn2 = nn.BatchNorm2d(64)
        # pool -> 50x50 -> 25x25

        # Block 3
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.bn3 = nn.BatchNorm2d(128)
        # pool -> 25x25 -> 12x12

        self.flatten = nn.Flatten()
        
        # Fully Connected Layers
        # 12*12*128 = 18432
        self.fc1 = nn.Linear(12 * 12 * 128, 512)
        self.dropout = nn.Dropout(0.5)
        self.fc2 = nn.Linear(512, 2) # 2 Classes: Male, Female

    def forward(self, x):
        x = self.pool(self.relu(self.bn1(self.conv1(x))))
        x = self.pool(self.relu(self.bn2(self.conv2(x))))
        x = self.pool(self.relu(self.bn3(self.conv3(x))))
        
        x = self.flatten(x)
        x = self.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return x

model = GenderCNN().to(device)
print(model)

# ==========================================
# 3. Training Loop
# ==========================================
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

num_epochs = 10
train_losses = []
val_accuracies = []

print("Starting Training...")

for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0
    
    for images, labels in train_loader:
        images = images.to(device)
        labels = labels.to(device)
        
        # Forward pass
        outputs = model(images)
        loss = criterion(outputs, labels)
        
        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        running_loss += loss.item()
    
    avg_train_loss = running_loss / len(train_loader)
    train_losses.append(avg_train_loss)
    
    # Validation
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for images, labels in val_loader:
            images = images.to(device)
            labels = labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
    
    acc = 100 * correct / total
    val_accuracies.append(acc)
    
    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {avg_train_loss:.4f}, Val Acc: {acc:.2f}%")

print("Training Finished.")

# ==========================================
# 4. Save the Model
# ==========================================
save_path = 'gender_cnn_model.pth'
torch.save(model.state_dict(), save_path)
print(f"Model saved to {save_path}")

# Helper to download from Colab
try:
    from google.colab import files
    files.download(save_path)
    print("Download triggered.")
except ImportError:
    print("Not running in Colab, file saved locally.")
