
# -*- coding: utf-8 -*-
"""Train_ResNet_Colab.ipynb

Automatically generated by Colaboratory.

# Gender Classification: ResNet18 (Transfer Learning)
"""

import os
# Auto-install dependencies
os.system('pip install kagglehub tqdm')

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader
from torchvision import datasets, transforms, models
import numpy as np
from tqdm import tqdm

# Check device
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# Dataset
try:
    import kagglehub
except ImportError:
    os.system('pip install kagglehub')
    import kagglehub

print("Downloading Dataset...")
dataset_path = kagglehub.dataset_download("cashutosh/gender-classification-dataset")
train_dir = os.path.join(dataset_path, 'Training')
val_dir = os.path.join(dataset_path, 'Validation')

# Transforms (ResNet expects 224x224 usually, but we can do 100x100 if we want consistency. 
# Let's stick to 100x100 for speed, ResNet adapts fine via average pooling at the end)
transform = transforms.Compose([
    transforms.Resize((100, 100)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]) # ImageNet norms
])

train_dataset = datasets.ImageFolder(train_dir, transform=transform)
val_dataset = datasets.ImageFolder(val_dir, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False)

# Model
print("Loading ResNet18...")
model = models.resnet18(pretrained=True)

# Freeze all layers
for param in model.parameters():
    param.requires_grad = False

# Replace head
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, 2)
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.fc.parameters(), lr=0.001)

# Train
epochs = 5
for epoch in range(epochs):
    model.train()
    running_loss = 0.0
    for images, labels in tqdm(train_loader, desc=f"Epoch {epoch+1}"):
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
    
    print(f"Epoch {epoch+1} Loss: {running_loss/len(train_loader):.4f}")
    
    # Validation
    model.eval()
    correct = 0; total = 0
    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
    print(f"Validation Accuracy: {100 * correct / total:.2f}%")

# Save
save_path = 'gender_resnet.pth'
torch.save(model.state_dict(), save_path)
print(f"Saved to {save_path}")

try:
    from google.colab import files
    files.download(save_path)
except: pass
